version: '3.8'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=DER
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        volumes:
            - postgres-db:/var/lib/postgresql/db
volumes:
    postgres-db:
