// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: audit.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const setCurrentUser = `-- name: SetCurrentUser :exec
INSERT INTO session_data (key, value)
VALUES ('current_user', $1)
ON CONFLICT (key)
DO UPDATE SET value = $1
`

// Sets the current user in the session_data table.
func (q *Queries) SetCurrentUser(ctx context.Context, value uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setCurrentUser, value)
	return err
}
